system:
  # Path where all intermediate and final results will be written:
  root_folder: /data/GPM_Sim/meta_evaluation

  # Path where data was stored using the CdmProcessor class:
  sequence_data_folder: /data/GPM_Sim/pretraining/person_sequence

  # Path where train data was stored using the GeneralPretrainedModelTools package:
  train_data_folder: /data/GPM_Sim/train
  
  # Path where train data was stored using the GeneralPretrainedModelTools package:
  test_data_folder: /data/GPM_Sim/test

  # Names of the sub folders holding the labels of the train data:
  train_label_sub_folders:
  - label_c1000000
  - label_c1000011
  - label_c1000022
  - label_c1000033
  - label_c1000044
  - label_c1000055
  - label_c1000066
  - label_c1000077
  - label_c1000088
  - label_c1000099

  # Names of the sub folders holding the labels of the train data:
  test_label_sub_folders:
  - label_c1000000
  - label_c1000011
  - label_c1000022
  - label_c1000033
  - label_c1000044
  - label_c1000055
  - label_c1000066
  - label_c1000077
  - label_c1000088
  - label_c1000099

  # Maximum number of CPU cores to use:
  max_cores: 5

  # Batch size for training and testing: (default: 32)
  batch_size: 32

  # Save the model every checkpoint_every epochs:
  checkpoint_every: 50

pretrained models:
- name: reference
  learning objectives:
    masked_concept_learning: yes
    mask_one_concept_per_visit: yes
    masked_visit_concept_learning: yes
    truncate_type: random
  training:
    train_fraction: 0.8
    num_epochs: 100
    learning_rate: 0.001
    weight_decay: 0.01
  model:
    max_sequence_length: 256
    concept_embedding: yes
    segment_embedding: yes
    age_embedding: yes
    date_embedding: yes
    visit_order_embedding: yes
    visit_concept_embedding: yes
    hidden_size: 100
    num_hidden_layers: 2
    num_attention_heads: 2
    intermediate_size: 100
    hidden_act: gelu
    embedding_combination_method: sum
    hidden_dropout_prob: 0.1
    attention_probs_dropout_prob: 0.1

- name: concat
  learning objectives:
    masked_concept_learning: yes
    mask_one_concept_per_visit: yes
    masked_visit_concept_learning: yes
    truncate_type: random
  training:
    train_fraction: 0.8
    num_epochs: 100
    learning_rate: 0.001
    weight_decay: 0.01
  model:
    max_sequence_length: 256
    concept_embedding: yes
    segment_embedding: yes
    age_embedding: yes
    date_embedding: yes
    visit_order_embedding: yes
    visit_concept_embedding: yes
    hidden_size: 100
    num_hidden_layers: 2
    num_attention_heads: 2
    intermediate_size: 100
    hidden_act: gelu
    embedding_combination_method: concat
    hidden_dropout_prob: 0.1
    attention_probs_dropout_prob: 0.1

- name: no_segments
  learning objectives:
    masked_concept_learning: yes
    mask_one_concept_per_visit: yes
    masked_visit_concept_learning: yes
    truncate_type: random
  training:
    train_fraction: 0.8
    num_epochs: 100
    learning_rate: 0.001
    weight_decay: 0.01
  model:
    max_sequence_length: 256
    concept_embedding: yes
    segment_embedding: no
    age_embedding: yes
    date_embedding: yes
    visit_order_embedding: yes
    visit_concept_embedding: yes
    hidden_size: 100
    num_hidden_layers: 2
    num_attention_heads: 2
    intermediate_size: 100
    hidden_act: gelu
    embedding_combination_method: sum
    hidden_dropout_prob: 0.1
    attention_probs_dropout_prob: 0.1
    
- name: no_visit_pred
  learning objectives:
    masked_concept_learning: yes
    mask_one_concept_per_visit: yes
    masked_visit_concept_learning: no
    truncate_type: random
  training:
    train_fraction: 0.8
    num_epochs: 100
    learning_rate: 0.001
    weight_decay: 0.01
  model:
    max_sequence_length: 256
    concept_embedding: yes
    segment_embedding: yes
    age_embedding: yes
    date_embedding: yes
    visit_order_embedding: yes
    visit_concept_embedding: yes
    hidden_size: 100
    num_hidden_layers: 2
    num_attention_heads: 2
    intermediate_size: 100
    hidden_act: gelu
    embedding_combination_method: sum
    hidden_dropout_prob: 0.1
    attention_probs_dropout_prob: 0.1
    
- name: mask_multi_concepts
  learning objectives:
    masked_concept_learning: yes
    mask_one_concept_per_visit: no
    masked_visit_concept_learning: yes
    truncate_type: random
  training:
    train_fraction: 0.8
    num_epochs: 100
    learning_rate: 0.001
    weight_decay: 0.01
  model:
    max_sequence_length: 256
    concept_embedding: yes
    segment_embedding: yes
    age_embedding: yes
    date_embedding: yes
    visit_order_embedding: yes
    visit_concept_embedding: yes
    hidden_size: 100
    num_hidden_layers: 2
    num_attention_heads: 2
    intermediate_size: 100
    hidden_act: gelu
    embedding_combination_method: sum
    hidden_dropout_prob: 0.1
    attention_probs_dropout_prob: 0.1
    
- name: four_hidden_layers
  learning objectives:
    masked_concept_learning: yes
    mask_one_concept_per_visit: yes
    masked_visit_concept_learning: yes
    truncate_type: random
  training:
    train_fraction: 0.8
    num_epochs: 100
    learning_rate: 0.001
    weight_decay: 0.01
  model:
    max_sequence_length: 256
    concept_embedding: yes
    segment_embedding: yes
    age_embedding: yes
    date_embedding: yes
    visit_order_embedding: yes
    visit_concept_embedding: yes
    hidden_size: 100
    num_hidden_layers: 4
    num_attention_heads: 2
    intermediate_size: 100
    hidden_act: gelu
    embedding_combination_method: sum
    hidden_dropout_prob: 0.1
    attention_probs_dropout_prob: 0.1
    
- name: four_att_heads
  learning objectives:
    masked_concept_learning: yes
    mask_one_concept_per_visit: yes
    masked_visit_concept_learning: yes
    truncate_type: random
  training:
    train_fraction: 0.8
    num_epochs: 100
    learning_rate: 0.001
    weight_decay: 0.01
  model:
    max_sequence_length: 256
    concept_embedding: yes
    segment_embedding: yes
    age_embedding: yes
    date_embedding: yes
    visit_order_embedding: yes
    visit_concept_embedding: yes
    hidden_size: 100
    num_hidden_layers: 2
    num_attention_heads: 4
    intermediate_size: 100
    hidden_act: gelu
    embedding_combination_method: sum
    hidden_dropout_prob: 0.1
    attention_probs_dropout_prob: 0.1
    
- name: hidden_size_200
  learning objectives:
    masked_concept_learning: yes
    mask_one_concept_per_visit: yes
    masked_visit_concept_learning: yes
    truncate_type: random
  training:
    train_fraction: 0.8
    num_epochs: 100
    learning_rate: 0.001
    weight_decay: 0.01
  model:
    max_sequence_length: 256
    concept_embedding: yes
    segment_embedding: yes
    age_embedding: yes
    date_embedding: yes
    visit_order_embedding: yes
    visit_concept_embedding: yes
    hidden_size: 200
    num_hidden_layers: 2
    num_attention_heads: 2
    intermediate_size: 100
    hidden_act: gelu
    embedding_combination_method: sum
    hidden_dropout_prob: 0.1
    attention_probs_dropout_prob: 0.1

- name: gpt
  learning objectives:
    next_token_prediction: yes
    truncate_type: random
  training:
    train_fraction: 0.8
    num_epochs: 100
    learning_rate: 0.001
    weight_decay: 0.01
  model:
    max_sequence_length: 256
    concept_embedding: yes
    segment_embedding: yes
    age_embedding: yes
    date_embedding: yes
    visit_order_embedding: yes
    visit_concept_embedding: yes
    hidden_size: 200
    num_hidden_layers: 2
    num_attention_heads: 2
    intermediate_size: 100
    hidden_act: gelu
    embedding_combination_method: sum
    hidden_dropout_prob: 0.1
    attention_probs_dropout_prob: 0.1

- name: gpt_visit_concepts
  learning objectives:
    next_visit_concepts_prediction: yes
    truncate_type: random
  training:
    train_fraction: 0.8
    num_epochs: 100
    learning_rate: 0.001
    weight_decay: 0.01
  model:
    max_sequence_length: 256
    concept_embedding: yes
    segment_embedding: yes
    age_embedding: yes
    date_embedding: yes
    visit_order_embedding: yes
    visit_concept_embedding: yes
    hidden_size: 200
    num_hidden_layers: 2
    num_attention_heads: 2
    intermediate_size: 100
    hidden_act: gelu
    embedding_combination_method: sum
    hidden_dropout_prob: 0.1
    attention_probs_dropout_prob: 0.1

fine-tuned models:
- name: reference
  pretrained models:
  - name: reference
  - name: concat
  - name: no_segments
  - name: no_visit_pred
  - name: mask_multi_concepts
  - name: four_hidden_layers
  - name: four_att_heads
  - name: hidden_size_200
  - name: reference
    pretrained_epoch: 50
  - name: gpt
  - name: gpt_visit_concepts
  learning objectives:
    label_prediction: yes
    truncate_type: tail
  training:
    train_fraction: 1
    num_epochs: 100
    num_freeze_epochs: 1
    learning_rate: 0.001
    weight_decay: 0.01
    
- name: no_freeze
  pretrained models:
  - name: reference
  learning objectives:
    label_prediction: yes
    truncate_type: tail
  training:
    train_fraction: 1
    num_epochs: 100
    num_freeze_epochs: 0
    learning_rate: 0.001
    weight_decay: 0.01
    
- name: simple_regression
  pretrained models:
  - name: reference
  learning objectives:
    label_prediction: yes
    truncate_type: tail
    simple_regression_model: yes
  training:
    train_fraction: 1
    num_epochs: 100
    learning_rate: 0.001
    weight_decay: 0.01